### ISSUE TITLE
STM32f103 A4963

### ISSUE THREAD

**Issue by pMertDogan** [descampsa/A4963#3]
Hello
I have STM32f103.Can i controll motor speed with spi? What ı need to write to reigsters using spi? For test i need connect allegro 4963 to motor or can i see analog values on osilascope without connecting the motor? Can you help me? I need level shifter for shift 3.3v to 5v ? (Spi)

**Comment by descampsa** [comment]
Motor speed is controlled by PWM, SPI is used to configure the controller parameters.
The speed example code, together with the datasheet, should give you an idea of what registers do. Note that there are a lot of parameters, but most (if not all) are optional and don't need to be changed.

Without a motor, the outputs you will measure will not be relevant, since the controller use feedback from the motor.

You do not need level shifter, SPI and PWM work with 3.3V (and are also 5V tolerant, IIRC)

Let me know if you want a schematic, i probably have that somewhere.

**Comment by pMertDogan** [comment]
I read the datasheet and i see i can controll motor speed using spi.I m wrong?
If i cant how can i drive it using pwm? what is spi data needed for it? what i need send? and i read i need PWM between 5Hz-1kHz.If you have schematic i can check my hardware desing.

Thanks

**Comment by descampsa** [comment]
The normal way to control speed is by pwm, and i don't see any register that allows to control it via spi, but maybe i miss something. What page of the datasheet are you refering to?

SPI is used to modify the various options of the controller (eg enable/disable, direction, brake, control mode, PI controller parameter, speed range, etc). For example if you want the controller to keep a constant speed independenlty of motor load, you need to select closed-loop speed control, and that can only be done with spi.

[brushless_controler_mini.pdf](https://github.com/descampsa/A4963/files/2635843/brushless_controler_mini.pdf)

**Comment by pMertDogan** [comment]
I see SPI controll on datasheet i will send it when i have time.Currently testing a4963 i dont have problem with hardware.I have one qeustion about controlling motor using pwm

I want basicly controll motor using PWM.How can i do this.Can you write steps to what i need to? Motor speed changed by PWM.I just turn motor without load.

Which spi value required to send  a4963 for controll motor with PWM? 
Which parameters i need config?

I send these values 

load_data_a4963(0b0001001000010100);//Config 0
Delay(100);
load_data_a4963(0b0011001111011111);//Config 1
Delay(100);
load_data_a4963(0b0101011110010011);//Config 2
Delay(100);
load_data_a4963(0b0111011101010010);//Config 3
Delay(100);
load_data_a4963(0b1001011100011111);//Config 4
Delay(100);
load_data_a4963(0b1011011101111000);//Config 5
Delay(100);
load_data_a4963(0b1111000000001011);//RUN

and my PWM is 500Hz Duty %50

whats wrong ?

**Comment by descampsa** [comment]
Looks good, the motor should start.
What happens? The motor doesn't move at all? It moves erratically?
Does the A4963 detect a fault? You can read the diagnostic register via spi for more details (eg a faulty transistor).
Is the power supply sufficiently powerfull? A motor may need a lot of current at startup.

**Comment by pMertDogan** [comment]
Motor doesnt start.My power suply is 3s lipo battery.I will check fault today and retry.

For Spi control i found this

DI[4:0], a 5-bit integer to allow control of the motor via the 
serial interface.


DI[4:0] Duty Cycle Control
DC = 7 + (n × 3)%
where n is a positive integer defined by DI[4:0].
For example, when DI[4:0] = 0, then serial duty cycle control is 
disabled and control reverts to the duty cycle of the PWM signal 
applied to the PWM input terminal.
The range of DC is 10% to 100%.

**Comment by pMertDogan** [comment]
I fixed problem.There is a problem with PWM cable.Its broken :) I replace it but now It moves erratically.I try fix it

**Comment by descampsa** [comment]
Yeah, it will work better with all the wires connected ;-)
For the erratic movement, you can try to play with the startup duty cycle and startup speed parameters.
Note that it will depend on the motor load, so you may want to experiment with the load on the motor.

**Comment by pMertDogan** [comment]
I can run other motor but unable run my own motor its looks like this.Other motor runs very easyly with any config its simple but unable run my motor its make a realy trouble.I can run it with 30A esc but a4963 cant run it thats stupid :/ 

My motor same as linked
https://www.banggood.com/Wholesale-XXD-A2212-KV1000-Brushless-Motor-H363-For-RC-Airplane-Quadcopter-p-57432.html?cur_warehouse=CN


You dont need PWM for controll motor speed.You can set motor speed using SPI.You need change Run Register 
Like this 

0xF0 09  //Motor speed is based on input pwm signal
0xF0 F9 //Full speed without pwm

So with this litle spi value you can change motor speed.

Thanks for helps
